### PR TITLE
Theme: Kasper

### LINKED ISSUE #3: Pick a theme
I looked through http://jekyllthemes.org/ and found these that I like:

* http://demo.getpoole.com/
* https://kiko.gfjaru.com/
* http://rosario.io/2013/11/10/kasper-theme-for-jekyll.html

@twingly/dev anyone else having some suggestions?

### PR DESCRIPTION
**Pull request by dentarg**
Close #3.

Screenshosts:

image

image

### CODE REVIEW

**Comment by dentarg** [comment]
Known issue, excerpt for next post isn't rendered:

image

Most likely because the theme tries to workaround [the limitations of Jekyll](https://github.com/jekyll/jekyll/issues/2860#issuecomment-68237526) with some hack using pages to achieve the "recommendation" feature. I tried adding ` | markdownify`, but it only made things worse. Also tried just to remove the excerpt, but then the title looked kinda lonely.

**Comment by jage** [comment]
screen shot 2016-01-05 at 16 57 28

LGTM!

**Comment by roback** [comment]
LGTM2

**Comment by dentarg** [comment]
I guess `markdownify` and `strip_html` was the trick, I don't think I tried that.

**Comment by dentarg** [comment]
> Seems like dots are included in the excerpt already

Or maybe added by `truncatewords`.

**Pull request merged**
